projeto_emprego/emprego/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.candidatos, name='candidatos'),
    path('candidatos/<int:id>/', views.detalhar_candidato, name='detalhar_candidato'),
    path('vagas/<int:id>/', views.detalhar_vaga, name='detalhar_vaga'),
    path('novo_candidato/', views.novo_candidato, name='novo_candidato'),
    path('nova_vaga/', views.nova_vaga, name='nova_vaga'),
]

projeto_emprego/projeto_emprego/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emprego.urls')),
]

projeto_emprego/emprego/models.py
from django.db import models

# Create your models here.
GENERO = [
    ('M', 'Masculino'),
    ('F', 'Feminino'),
]
ESCOLARIDADE = [
    ('ENSINO_FUNDAMENTAL','Ensino Fundamental'),
    ('ENSINO_MEDIO','Ensino Médio'),
    ('CURSO_TECNICO', 'Curso Técnico'),
    ('CURSO_SUPERIOR', 'Curso Superior')
]
AREA = [
    ('DESENVOLVEDOR', 'Desenvolvedor'),
    ('QA','Tester'),
    ('LIDER', 'Lider Técnico')
]
CONTRATO = [
    ('PJ', 'Pessoa Júrídica'),
    ('CLT', 'CLT')
]

class Vaga(models.Model):
    titulo = models.CharField(max_length=50)
    area = models.CharField(max_length=15, choices=AREA)
    tipo_contrato = models.CharField(max_length=15, choices=CONTRATO)
    descricao = models.CharField(max_length=50)
    def __str__(self):
        return self.titulo
        
class Candidato(models.Model):
  
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50)
    data_nascimento = models.DateField()
    genero = models.CharField(max_length=1, choices=GENERO)
    email = models.CharField(max_length=50)
    escolaridade = models.CharField(max_length=50, choices=ESCOLARIDADE)
    vaga = models.ForeignKey(Vaga, on_delete=models.CASCADE)
    def __str__(self):
        return self.nome
        

projeto_emprego/emprego/forms.py
from django import forms
from .models import Candidato, Vaga

# Formulário para Curso
class CandidatoForm(forms.ModelForm):
    class Meta:
        model = Candidato 
        fields = ['nome','sobrenome','data_nascimento','genero','email','escolaridade','vaga'] 
class VagaForm(forms.ModelForm):
    class Meta:
        model = Vaga 
        fields = ['titulo','area','tipo_contrato','descricao'] 

projeto_emprego/emprego/views.py
from django.shortcuts import render,redirect
from .models import Candidato, Vaga
from .forms import CandidatoForm, VagaForm
# Create your views here.
def candidatos(request):
    candidatos = Candidato.objects.all()
    resp = {
        'candidatos' : candidatos
    }
    return render(request, 'emprego/candidatos.html', resp)
def detalhar_candidato(request, id):
    candidato = Candidato.objects.get(id=id)
    resp = {
        'candidato' : candidato
    }
    return render(request, 'emprego/detalhar_candidato.html', resp)
def detalhar_vaga(request, id):
    vaga = Vaga.objects.get(id=id)
    resp = {
        'vaga' : vaga
    }
    return render(request, 'emprego/detalhar_vaga.html', resp)

def novo_candidato(request):
    if request.method == 'POST':
        form = CandidatoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('candidatos') 
    else:
        form = CandidatoForm()

    return render(request, 'emprego/novo_candidato.html', {'form': form})

def nova_vaga(request):
    if request.method == 'POST':
        form = VagaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('candidatos') 
    else:
        form = VagaForm()

    return render(request, 'emprego/nova_vaga.html', {'form': form})

projeto_emprego/emprego/templates/emprego/candidatos.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidatos</title>
</head>

<body>
    <h1>Lista de Candidatos</h1>
    <a href="{% url 'novo_candidato' %}">Novo Candidato</a>
    <a href="{% url 'nova_vaga' %}">Nova Vaga</a>
    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Sobrenome</th>
                <th>Gênero</th>
                <th>Vaga</th>
            </tr>
        </thead>
        <tbody>
            {% for candidato in candidatos %}
            <tr>
                <td><a href="{% url 'detalhar_candidato' candidato.id%}">{{ candidato.nome }}</a></td>
                <td>{{ candidato.sobrenome }}</td>
                <td>{{ candidato.get_genero_display }}</td>
                <td><a href="{% url 'detalhar_vaga' candidato.vaga.id%}">{{ candidato.vaga.titulo }}</a></td>
            </tr>
            {% empty %}

            {% endfor %}
        </tbody>
    </table>

</body>

</html>

projeto_emprego/emprego/templates/emprego/detalhar_candidato.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidato</title>
</head>

   <h1>Detalhes do Candidato</h1>

    <div class="detalhe">
        <p><strong>Nome:</strong> {{ candidato.nome }} {{ candidato.sobrenome }}</p>
        <p><strong>Email:</strong> {{ candidato.email }}</p>
        <p><strong>Data de Nascimento:</strong> {{ candidato.data_nascimento }}</p>
        <p><strong>Gênero:</strong> {{ candidato.get_genero_display }}</p>
        <p><strong>Escolaridade:</strong> {{ candidato.get_escolaridade_display }}</p>
        <p><strong>Vaga Aplicada:</strong> {{ candidato.vaga.titulo }}</p>
        <p><strong>Área:</strong> {{ candidato.vaga.get_area_display }}</p>
    </div>

    <a href="{% url 'candidatos' %}">Voltar à lista de candidatos</a>

</html>

projeto_emprego/emprego/templates/emprego/detalhar_vaga.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Detalhes da Vaga</title>
</head>
<body>
    <h1>Detalhes da Vaga</h1>

    <div class="detalhe">
        <p><strong>Título:</strong> {{ vaga.titulo }}</p>
        <p><strong>Área:</strong> {{ vaga.get_area_display }}</p>
        <p><strong>Tipo de Contrato:</strong> {{ vaga.get_tipo_contrato_display }}</p>
        <p><strong>Descrição:</strong> {{ vaga.descricao }}</p>
    </div>

    <a href="{% url 'candidatos' %}">Voltar para a lista de candidatos</a>
</body>
</html>

projeto_emprego/emprego/templates/emprego/nova_vaga.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidatos</title>
</head>

<h1>Nova Vaga</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Cadastrar Vaga</button>

</form>

<a href="{% url 'candidatos'%}">
    <button>
        Voltar
    </button>
</a>



</html>

projeto_emprego/emprego/templates/emprego/novo_candidato.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidatos</title>
</head>

<h1>Novo candidato</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Cadastrar Candidato</button>

</form>
<a href="{% url 'candidatos'%}">
    <button>
        Voltar
    </button>
</a>

</html>